version: '3'

services:
  db:
    image: mysql:5.7
    container_name: blog_db
    restart: always
    env_file:
      - ./mysql/.env
    environment:
      MYSQL_DATABASE: $$DATABASE_NAME
      MYSQL_USER: $$DATABASE_USER
      MYSQL_PASSWORD: $$DATABASE_PASSWORD
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d:ro
  lambda:
    build: ./aws
    container_name: blog_lambda
    ports:
      - '4000:3000'
      - '4001:3002'
    environment:
      NODE_ENV: develop
      HOST: '0.0.0.0'
      PORT: 3000
    volumes:
      - ./aws:/app
      - lambda_node_modules:/app/node_modules
    depends_on:
      - db
  next:
    build: ./next
    container_name: blog_next
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: develop
    volumes:
      - ./next:/app
      - next_node_modules:/app/node_modules
    depends_on:
      - lambda

volumes:
  lambda_node_modules:
  next_node_modules:
