version: '3'

services:
  lambda:
    build: ./aws
    container_name: blog_lambda
    ports:
      - '4000:3000'
      - '4001:3002'
    environment:
      NODE_ENV: develop
      HOST: '0.0.0.0'
      PORT: 3000
    volumes:
      - ./aws:/app
      - lambda_node_modules:/app/node_modules

volumes:
  lambda_node_modules:
